### ISSUE TITLE
New parking event for same reg.num will override previous event.

### ISSUE THREAD

**Issue by PerttuP** [DriverCity/SPARK#12]
Making new parking event for a register number that already is registered for parking will override previous event regardless of expiration time. E.g. if first event would expire in an hour, and second in 5 minutes, the latter will override previous. This should be: latter event will override previous event only if it would expire later.

**Comment by chartjunk** [comment]
This is not an issue, since this is analogous to using the traditional system in such a way, that

1. Purchase 1 hour parking permit for the area 0
2. Throw 1 hour parking permit away
3. Purchase 5 minutes parking permit for the area 0.

Instead, we should ask the user confirmation on the app side, whether he/she wants to discard the previous event or not. In a bigger picture, this is part of a bigger problem of not having an authentication, as anyone could remove the parking event of anyone else just by registering a parking disc parking with the same register number.
